# 넘파이(NumPy)

In [8]:
# 머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다.
# 넘파이는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지이다.
# 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장한다.

## 넘파이 ndarray 개요

In [37]:
# 넘파이 모듈 호출하기
import numpy as np

# 넘파이의 기반 데이터 타입은 ndarray이다.
# ndarray를 이요해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있다.
# 넘파이 array() 함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행한다.
# 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로
# 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있다.

In [38]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array형태:', array1.shape)

array2 = np.array([[1, 2, 3,],
                    [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array ([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [39]:
# np.array() 사용법은 매우 간단하다.
# ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환한다.
# ndarray.shape는 ndarray의 차원과 크기를 튜플(tuple) 형태로 나타내 준다.

# [1,2,3]인 array1의 shape는 (3,)이다. 
# 이는 1차원 array로 3개의 데이터를 가지고 있음을 뜻한다.

# [[1,2,3],[2,3,4]]인 array2의 shape는 (2,3)이다.
# 이는 2차원 array로 2개의 로우와 3개의 칼럼으로 구성되어 2*3=6개의 데이터를 가지고 있음을 뜻한다.

# [[1,2,3]]인 array3의 shape는 (1,3)이다.
# 이는 1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터를 의미한다.

# 이 차이를 이해하는 것은 매우 중요하다.
# 머신러닝 알고리즘과 데이터 세트 간의 입출력과 변환을 수행하다 보면 데이터값으로는 서로 동일하나
# 차원이 달라서 오류가 발생하는 경우가 빈번하다.
# 이 경우 명확히 차원의 차수를 변환하는 방법을 알아야 이런 오류를 막을 수 있다.

In [40]:
# 각 array의 차원을 ndarray.ndim을 이용해 확인할 수 있다.
print('array1:{:0}차원, array2:{:1}차원, array3: {:2}차원'.format(array1.ndim,
                                                               array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3:  2차원


In [41]:
# array1은 1차원, array3은 2차원임을 알 수 있다.
# array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용된다.
# 리스트 []는 1차원, 리스트의 리스트는 [[]]는 2차원과 같은 형대로 배열과 차원의 크기를
# 쉽게 표현할 수 있기 때문이다.

## ndarray의 데이터 타입

In [42]:
# ndarray내의 데이터 값은 숫자, 문자열, 불 등이 모드 가능하다.
# ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다.
# 즉, 한개의 ndarray 객체에 int와 float가 함께 있을 수 없다.

In [43]:
# ndarray내의 데이터 타입은 dtype 속성으로 확인할 수 있다.
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [44]:
# 서로 다른 데이터 타입을 가질 수 있는 리스트와는 다르게 ndarray 내의 데이터 타입은
# 그 연산의 특성과 같은 데이터 타입만 가능하다고 했는데, 만약 다른 데이터 유형이 섞여 있는
# 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [45]:
# int형과 string형이 섞여 있는 리스트와 int형과 float형이 섞여 있는 리스트를
# ndarray로 변경하면 데이터값의 타입이 어떻게 되는지 확인해보자.
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array2.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] <U21


In [46]:
# ndarray 내 데이터 값의 타입 변경도 astype() 메서드를 이용할 수 있다.
# astype()에 인자로 원하는 타입을 문자열로 지정하면 된다.
# 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 떄 많은 메모리가 사용되는데,
# 메모리를 더 절약해야 할 때 보통 이용된다.

In [47]:
# 파이썬 기반의 머신러닝 알고리즘은 대부분 메모리로 데이터를 전체 로딩한 다음 이를 기반으로
# 알고리즘을 적용하기 떄문에 대용량의 데이터를 로딩할 때는 수행속도가 느려지거나
# 메모리 부족으로 오류가 발생할 수 있다.

In [48]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

In [49]:
# 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 
# 쉽게 생성해야 할 필요가 있는 경우가 발생할 수 있다.
# 이 경우 arange(), zeros(), ones()를 이용해 쉽게 ndarray를 생성할 수 있다.
# 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용된다.

In [50]:
# arange()는 함수 이름에서 알 수 있듯이 파이썬 표준 함수인 range()와 유사한 가능을 한다.
# 0부터 함수 인자 값 -1 까지의 값을 순차적으로 ndarray의 데이터 값으로 변환해 준다.

In [51]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [52]:
# dafault 함수 인자는 stop 값이며, 0부터 stop 값인 10에서 -1을 더한 9까지의
# 연속 숫자 값으로 구성된 1차원 ndarray를 만들어 준다.
# range와 유사하게 start 값도 부여해 0이 아닌 다른 값부터 시작한 연속 값으 부여할 수도 있다.

In [53]:
# zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 
# 해당 shape를 가진 ndarray를 반환한다.

In [54]:
zero_array = np.zeros((3, 2), dtype ='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [55]:
# ones()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운
# 해당 shape를 가진 ndarray를 반환한다.
# 함수 인자로 dtype을 정해주지 않으면 dafult로 flast64형의 데이터로 ndarray를 채운다.

In [56]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape( )

In [57]:
# reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환한다.
# 변환을 원하는 크기를 함수 인자로 부여하면 된다.

In [58]:
# 0~9까지의 1차원 ndarray를 (2로우, 5칼럼), (5로우, 2칼럼) 형태로 2차원 ndarray로 변환하는 예제
array1 = np.arange(10)
print('array1:\n', array1)

array2 = np.reshape(2, 5)
print('array2:\n', array2)

array3 = np.reshape(5, 2)
print('array3: \n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 1 into shape (5,)

In [59]:
# reshape()를 더욱 효율적으로 사용하는 경우는 인자로 -1을 적용하는 경우일 것이다.
# -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다.

In [60]:
# reshape()의 -1값을 인자로 적용한 경우의 예제
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [62]:
# array1은 1차원 ndarray로 0~9까지의 데이터를 가지고 있다.
# array2는 array1.reshape(-1, 5)로, 로우 인자가 -1, 칼럼 인자가 5이다.
# 이것은 array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개의 칼럼에 맞는
# 로우를 자동으로 새롭게 생성해 변환하라는 의미이다.
# 즉, 10개의 1차원 데이터와 호환할 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로
# 2X5의 2차원 ndarray로 변환하는 것이다.

# array1.reshape(5, -1)도 마찬가지이다.
# 10개의 1차원 데이터와 호환할 수 있는 고정된 5개의 로우에 맞는 칼럼은 2이므로 
# 5X2의 2차원 ndarray로 변환하는 것이다.

In [63]:
# -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없다.
# 10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로는 변경할 수 없기에
# reshape(-1, 4)는 에러가 발생한다.

In [64]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [65]:
# -1 인자는 reshape(-1, 1)와 같은 형대로 자주 사용된다.
# reshape(-1, 1)은 원본 ndarray가 어떤 형태라도 2차원이고,
# 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.
# 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 
# 각각의 ndarray의 형태를 통일해 유용하게 사용된다.

In [67]:
# reshape(-1, 1)을 이용해 3차원을 2차원으로, 1차원을 2차원으로 변경하는 예제
# tolist() 메서드를 이용해 리스트 자료형으로 변환 할 수 있다.
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing) 

In [70]:
# 인덱싱의 특징
# 1. 특정 데이터만 추출: 원하는위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다.
# 2. 슬라이싱(Slicing): 슬라이싱은 연속된 인덱스 상의 ndarray를 추출하는 방식이다.
#   ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 위치에 있는
#   데이터의 ndarrray를 반환한다.
#3. 팬시 인덱싱(Fency Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해
#   해당 위치에 있는 데이터의 ndarray를 반환한다.
#4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로
#   True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다.

### 단일 값 추출

In [73]:
# 1부터 9까지의 1차원 ndarray생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [74]:
# 인덱스는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치이므로 데이터 값 3을 의미한다.
# 인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출할 수 있다.
# 인덱스 -1는 맨 뒤의 데이터 값을 의미하고, -2는 맨 뒤에서 두 번째 있는 데이터 값이다.

In [77]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [78]:
# 단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능하다.
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [79]:
# 1차원과 2차원 ndarray의 데이터 접근 차이는 
# 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근한다.

In [80]:
# 1차원 ndarray를 2차원의 3X3 ndarray로 변환한 후 
# [row, col]을 이용해 2차원 ndarray에서 데이터를 추출하는 예제
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2)

print('(row=0, col=0 index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1 index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0 index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2 index 가리키는 값:', array2d[2, 2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
(row=0, col=0 index 가리키는 값: 1
(row=0, col=1 index 가리키는 값: 2
(row=1, col=0 index 가리키는 값: 4
(row=2, col=2 index 가리키는 값: 9


In [82]:
# axis 0이 로우 방향 축, axis 1이 ㅏㄹ럼 방향 축임을 이해하는 것이 중요하다.
# 축 기반의 연산에서 axis가 생략되면 axis 0을 의미한다.

### 슬라이싱 

In [90]:
# ':' 기호를 이용해 '연속한 데이터'를 슬라이싱해서 '추출'할 수 있다.
# 단일 데이터 값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터는
# 모두 ndarray 타입니다.
# ':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스를 '종료 인덱스 -1'의 위치에 있는
# 데이터의 ndarray를 반환한다.

In [84]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [85]:
# 슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략이 가능하다.
# ':' 기호 앞의 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주한다.
# ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주한다.
# ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스를 간주한다.

In [86]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [89]:
# 2차원 ndarray에서 슬라이싱으로 데이터에 접근하기.
# 콤마(,)로 로우와 칼럼 인덱스를 지칭한다.
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)
print('\n')
print('array2d[0:2,0:2] \n', array2d[0:2, 0:2])
print('\n')
print('array2d[1:3,0:3] \n', array2d[1:3, 0:3])
print('\n')
print('array2d[1:3,:] \n', array2d[1:3, :])
print('\n')
print('array2d[:,:] \n', array2d[:, :])
print('\n')
print('array2d[:2,1:] \n', array2d[:2, 1:])
print('\n')
print('array2d[:2,0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array2d[0:2,0:2] 
 [[1 2]
 [4 5]]


array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]


array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]


array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array2d[:2,1:] 
 [[2 3]
 [5 6]]


array2d[:2,0] 
 [1 4]


In [91]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다.
# 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환한다.

In [93]:
print(array2d[0])
print('array2d[0] shape:', array2d[0].shape)
print(array2d[1])
print('array2d[1] shape:', array2d[1].shape)

[1 2 3]
array2d[0] shape: (3,)
[4 5 6]
array2d[1] shape: (3,)


### 팬시 인덱싱

In [94]:
# 팬시 인덱싱(Fancy Indexing)은 '리스트'나 'ndarray'로 인덱스 집합을 지정하면
# 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다.

In [97]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[0, 1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

In [98]:
# '조건 필터링'과 '검색'을 동시에 할 수 있기 때문에자주 사용된다.
# 불린 인덱싱은 ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 적용하면 된다.

In [99]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [100]:
# 조건 필터링의 원리
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [101]:
# 조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 [ ] 내에 입력하면 False 값은 무시하고
# True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환하게 된다.

In [107]:
# 불린 ndarray를 만들고 이를 array1d[]내에 인덱스로 입력하면 동일한 데이터 세트가 반환된다.
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [108]:
# 직접 인덱스 집합을 만들어 대입한 것과 동일하다.
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


## 행렬의 정렬 - sort( )와 argsort( ) 

In [109]:
# 넘파이에서 행렬을 정렬하는 대표적인 방법 np.sort(), ndarray.sort()와
# 정렬된 행렬의 인덱스를 반환하는 argsort()

### 행렬 정렬 

In [116]:
# 넘파이의 행렬 정렬은 np.sort()와 ndarray.sort() 방식이 있다.
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

원본 행렬: [3 1 9 5]


In [117]:
# np.sort()는 넘파이에서 sort()를 호출하는 방식.
# 원 행렬은 그대로 유지한 채 '정렬된 행렬'을 '반환'한다.

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]


In [119]:
# np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환했다.

In [122]:
# ndarray.sort()는 행렬 자체에서 sort()를 호출하는 방식.
# ndarray.sort()는 '원 행렬 자체'를 '정렬한 형태'로 '변환'하며 반환 값은 None이다.

# adarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)

org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [123]:
# ndarray.sort()는 원본 행렬 자체를 정렬한 값으로 변환했다.

In [124]:
# np.sort()나 ndarrray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬한다.
# 내림차순 정렬 하기 위해서는 [::-1]을 적용한다.

In [126]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [133]:
# 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있다.
array2d = np.array([[8, 12],
                   [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
print('\n')
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]


칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기 

In [134]:
# 원본행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용한다.
# np.argsort()는 정렬 행렬의 원본 행렬 '인덱스'를 ndarray형으로 반환한다.

In [135]:
# np.argsort()를 이용해 원본 행렬의 정렬 시 행렬 인덱스 값을 구하기
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [136]:
# 내림차순으로 정렬 시 원본 행렬의 인덱스를 구하는 것도 np.argsort()[::-1]를 적용한다.
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)[::-1]
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [137]:
# 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없다.
# 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 한다.

In [140]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기 

### 행렬내적(행렬 곱) 

In [141]:
# 행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능하다.
# 행렬 내적의 특성으로 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행의 개수가 동일해야 내적 연산이 가능하다.

In [143]:
A = np.array([[1, 2, 3],
            [4, 5, 6]])

B = np.array([[7, 8],
            [9, 10],
            [11, 12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치행렬 

In [144]:
# 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 전치행렬 이라고 한다.
# 넘파이의 transpose()를 이용해 전치 행렬을 구할 수 있다.

In [145]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬\n', transpose_mat)

A의 전치 행렬
 [[1 3]
 [2 4]]


In [146]:
# ------ End ------